### ISSUE TITLE
https://sccc.kr/scon/2019 에서 사이드바 링크 오류

### ISSUE THREAD

**Issue by bbvch13531** [ssu-sccc/ssu-sccc.github.io#1]
sccc.kr/scon/2019 에서 사이드바에 있는 항목들 클릭하면
링크는 `https://sccc.kr/scon/2019/#portfolio` 이렇게 바뀌는데  화면은 바뀌지 않습니다.
원래 링크는 `https://sccc.kr/#portfolio` 이어서 그런 것 같습니다.

사이드바 항목의 링크를 수정하면 될 것 같습니다.

ssu-sccc.github.io/_includes/sidebar.html에 있는 
```
  <a class="item" href={{ site.baseurl | append: "#services"}}>Who we are</a>
    <a class="item" href={{ site.baseurl | append: "#activity"}}>Activity</a>
    <a class="item" href={{ site.baseurl | append: "#portfolio"}}>Portfolio</a>
    <a class="item" href={{ site.baseurl | append: "#team"}}>Team</a>
```
이 코드에서 append를 하기 때문에 유효하지 않은 링크가 연결된 것 같습니다.

**Comment by ssu-sccc** [comment]
수정하였습니다. 제보 감사합니다 :)
